### ISSUE TITLE
Reordering and grouping the languages list.

### ISSUE THREAD

**Issue by RXB83** [palash25/best-practices-checklist#13]
The languages list is now semi-random, it's mostly by addition. This makes it harder to find the language you are looking for, especially when the list grows longer and longer.
If the languages in the list are grouped by language family and alphabetised it would help finding them quicker.

**Comment by palash25** [comment]
Hi @RXB83 thanks for raising the issue, you can go ahead and make a PR for this if you want.

**Comment by RXB83** [comment]
I'll, when I've done the work in my fork.

**Comment by RXB83** [comment]
@palash25 I've completed the first part of the rework and added a PR.

**Comment by palash25** [comment]
Yes @RXB83 I saw the PR I will review it in a few days, right now I don't have good internet so can't do it right away

**Comment by RXB83** [comment]
@palash25 No problem. I only reordered the index list and reordered the listings. I didn’t remove or added any thing.

**Comment by RXB83** [comment]
@palash25 Updated to the new version of your master document.

**Comment by palash25** [comment]
thanks @RXB83 I can't merge it right away since it still has conflicts and right now I am busy with my exams. Will get back to it once I am done with my exams, I haven't forgotten about it. Sorry for the delay.

**Comment by RXB83** [comment]
That was because of an  PR #22 was done before PR #14

**Comment by RXB83** [comment]
I finished family groupings too.
